name: Node.js Package

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '14'  # or your desired Node.js version
        registry-url: https://npm.pkg.github.com/
    - run: |
        echo "running NPM as $(npm whoami --registry=https://npm.pkg.github.com)"
        npm ci
        npm test
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
